# Generated by Django 5.1 on 2024-10-31 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_algro', '0002_musicsheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicsheet',
            name='image_path',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
